name: Staging test and merge

on:
  schedule:
    - cron: '25 19 * * *'

jobs:
  testes-e-migracao:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Especifique a versão do Python que você está usando

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes Python
        run: python manage.py tests

      - name: Criar nova branch
        id: create_branch
        run: |
          git checkout staging
          git checkout -b qa-$(date +'%Y%m%d')
          git push origin qa-$(date +'%Y%m%d')
          BRANCH_NAME="qa-$(date +'%Y%m%d')"
          echo "::set-output name=branch_name::$BRANCH_NAME"
          
      # - name: Deploy
      #   run: | 
      #   zappa update x