name: Deploy to AWS Lambdas - Development

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar pipenv
        run: |
          sudo apt-get install libpq-dev -y
          pip install pipenv

      - name: Instalar dependências
        run: |
          pipenv install

      - name: Set up dependency caching for faster installs
        uses: actions/cache@v3
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !take5-system-configs.xlsx

  deploy:
    name: Teste
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
